
<div class="header">
  <h1 class="page-title"> Salas de las Sucursales "<?php echo $this->name; ?>"<a href="/subsidiary/index/id/<?php echo $this->idSubsidiary;  ?>" class="lnkHBack">Volver >></a></h1>
</div>
<div class="clearfix padding-bottom">
  <div class="pull-right">
    <button id="lnkHall" data-target="#tplHall" class="btn btn-primary"><i class="fa fa-plus"></i>&nbsp;&nbsp;Crear nueva Sala</button>
  </div>
</div>
<table id="datatable" class="table">
  <thead>
    <tr>
      <th>Sucursal</th>
      <th>Dirección</th>
      <th>Departamento</th>
      <th class="tdAction">Acciones</th>
    </tr>
  </thead>
  <tbody></tbody>
</table>
<script type="text/template" id="tplhall">
  <div tabindex="-1" aria-hidden="true" class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <form id="frmSubsidiary">
          <div class="modal-header">
            <button type="button" data-dismiss="modal" class="close"><span>&times;</span><span class="sr-only">Close</span></button>
            <h3>{{ if(typeof id!='undefined'){ }}Modificar Sucursal{{ }else{ }}Crear Sucursal{{ } }}</h3>
          </div>
          <div class="modal-body">
            <div class="form-group">
              <label>Ubicación:</label>
              <select name="idubigeo" id="idubigeo" class="form-control input-sm">
                <option value="">Seleccione una Ubicación</option>{{ _.map(yOSON.ubigeo,function(json,id){ }}
                <option value="{{= id }}" {{ if(typeof idubigeo!='undefined' && idubigeo==id){ }}selected="selected"{{ } }}>{{= json.name }}</option>
                {{ }); }}
              </select>
            </div>
            <div class="form-group">
              <label>Nombre de la Sucursal:</label>
              <input type="text" name="name" value="{{ if(typeof name!='undefined'){ }}{{= name }}{{ } }}" class="form-control input-sm"/>
              <input type="hidden" name="idcompany" value="{{= yOSON.idCompany }}"/>{{ if(typeof id!='undefined'){ }}
              <input type="hidden" name="id" value="{{= id }}"/>{{ } }}
            </div>
            <div class="form-group">
              <label>Dirección:</label>
              <textarea class="form-control input-sm" name="address">{{ if(typeof address!='undefined'){ }}{{= address }}{{ } }}</textarea>
            </div>
          </div>
          <div class="modal-footer">
            <button data-dismiss="modal" type="button" class="btn btn-default">Cancel</button>
            <button type="submit" class="btn btn-primary">Guardar</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</script>