
<head>
  <meta charset="utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
  <title>Cines Uvk</title>
  <meta name="title" content="CinesUvk"/>
  <meta name="description" content="CinesUvk"/>
  <meta name="keywords" content="CinesUvk, Administrador CinesUvk"/>
  <meta name="author" content=""/>
  <meta name="viewport" content="width=device-width"/>
  <meta name="language" content="es"/>
  <meta name="robots" content="index,follow"/>
  <meta property="og:site_name" content=""/>
  <meta property="og:type" content="website"/>
  <meta property="og:title" content="CinesUvk"/>
  <meta property="og:description" content="CinesUvk"/>
  <meta property="og:url" content=""/>
  <meta property="og:image" content=""/>
  <link href="" rel="image_src" type="image/jpeg"/>
  <link href="<?php echo STATIC_URL; ?>img/favicon.ico" rel="icon" type="image/vnd.microsoft.icon"/>
  <link href="<?php echo STATIC_URL; ?>img/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Open+Sans:400,700"/>
  <link type="text/css" rel="stylesheet" href="<?php echo STATIC_URL; ?>css/bootstrap.css?v=123"/>
  <link type="text/css" rel="stylesheet" href="<?php echo STATIC_URL; ?>css/font-awesome.css?v=123"/>
  <link type="text/css" rel="stylesheet" href="<?php echo STATIC_URL; ?>css/admin.css?v=123"/><!--[if lt IE 9]>
  <script src="<?php echo STATIC_URL; ?>js/vendor/html5shiv.js"></script>
  <script src="<?php echo STATIC_URL; ?>js/vendor/selectivizr.js"></script><![endif]-->
</head>