
<div class="sidebar-nav">
  <ul>
    <li><a href="/" class="nav-header"><i class="fa fa-fw fa-dashboard"></i>&nbsp;Dashboard</a></li>
    <li><a href="/company" class="nav-header"><i class="fa fa-fw fa-chain"></i>&nbsp;Clientes<span class="label label-danger"></span></a></li>
    <li><a href="/movie" class="nav-header"><i class="fa fa-fw fa-ticket"></i>&nbsp;Campañas<span class="label label-danger"></span></a></li>
    <li><a href="/genre" class="nav-header"><i class="fa fa-fw fa-folder"></i>&nbsp;Generos</a></li>
    <li><a href="/chain" class="nav-header"><i class="fa fa-fw fa-tags"></i>&nbsp;Publicidad</a></li>
  </ul>
</div>