
<!doctype html>
<!--[if lt IE 7]> <html class="lt-ie9 lt-ie8 lt-ie7" lang="es"> <![endif]-->
<!--[if IE 7]>    <html class="lt-ie9 lt-ie8" lang="es"> <![endif]-->
<!--[if IE 8]>    <html class="lt-ie9" lang="es"> <![endif]-->
<!--[if gt IE 8]> <html lang="es"> <![endif]-->
<?php echo $this->render("include/head.phtml"); ?>
<body><?php echo $this->render("include/header.phtml"); ?>
  <div id="wrapper"><?php echo $this->render("include/menu.phtml"); ?>
    <div class="content">
      <div class="jqAlert alert hid">
        <button type="button" class="close"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button><span class="jqAlert-desc"></span>
      </div><?php echo $this->layout()->content ?>
      <?php echo $this->render("include/footer.phtml"); ?>
    </div>
  </div>
  <script type="text/javascript">
    var yOSON ={
     "modulo":"<?php echo $this->dataYOSON['module']?>",
     "controller":"<?php echo $this->dataYOSON['controller']?>",
     "action":"<?php echo $this->dataYOSON['action']?>",
     "baseHost":"<?php echo SITE_URL?>",
     "statHost":"<?php echo STATIC_URL?>",
     "eleHost":"<?php echo DINAMIC_URL?>",
     "statVers":"?12232",
     <?php foreach ($this->yosonVars as $key => $value) : 
      echo '"'.$key.'":'.$value.', '; 
      endforeach; 
      echo '"min":"","AppCore":{},"AppSandbox":{},"AppSchema":{"modules":{},"requires":{}'
     ?>  
     }
    };
  </script>
  <script type="text/javascript" src="<?php echo STATIC_URL?>js/vendor/vendor.js"></script>
  <script type="text/javascript" src="<?php echo STATIC_URL?>js/library/library.js"></script>
</body>