
<div class="dialog">
  <div class="panel panel-default">
    <p class="panel-heading no-collapse">Login</p>
    <div class="panel-body">
      <form action="/login/auth" method="post">
        <div class="form-group">
          <label>Usuario</label>
          <input type="text" name="user" class="form-control span12"/>
        </div>
        <div class="form-group">
          <label>Contraseña</label>
          <input type="password" name="pass" class="form-control span12"/>
        </div>
        <div class="control alg-right">
          <button type="submit" class="btn btn-primary">Sign In</button>
        </div>
      </form>
    </div>
  </div>
  <?php /* ?><p><a href="/login/lost-password">¿Olvidaste tu contraseña?</a></p><?php */ ?>
</div>