
<div class="dialog">
  <div class="panel panel-default">
    <p class="panel-heading no-collapse">Resetear tu contraseña</p>
    <div class="panel-body">
      <form method="post" action="/login/lost-password">
        <div class="form-group">
          <label>Usuario o Email</label>
          <input type="text" name="email" class="form-control span12"/>
        </div>
        <div class="control alg-right">
          <button type="submit" class="btn btn-primary">Resetear password</button>
        </div>
      </form>
    </div>
  </div>
  <p><a href="/login">Logueate con tu cuenta</a></p>
</div>