
<div class="docCtn">
  <div class="loginCtn">
    <div class="heartbeat"></div>
    <div class="title">Médicos</div>
    <div class="lgnBox fix">
      <div class="flap sprites icFlapLg"></div>
      <div class="formTitle">REGISTRO</div>
      <form id="#form" method="POST" action="/login/register" class="formCtn">
        <div class="actionInput">
          <label for="email" class="sprites icLEmail formIc"></label>
          <input type="text" name="email" id="email" placeholder="email" class="passw"/>
        </div>
        <div class="actionInput">
          <label for="name" class="sprites icLInfo formIc"></label>
          <input type="text" name="name" id="name" placeholder="Nombre" class="passw"/>
        </div>
        <div class="actionInput">
          <label for="paternal" class="sprites icLInfo formIc"></label>
          <input type="text" name="paternal" id="paternal" placeholder="Apellido Paterno" class="passw"/>
        </div>
        <div class="actionInput">
          <label for="maternal" class="sprites icLInfo formIc"></label>
          <input type="text" name="maternal" id="maternal" placeholder="Apellido Materno" class="passw"/>
        </div>
        <div class="actionInput">
          <label for="pass" class="sprites icPassLg formIc"></label>
          <input type="password" name="pass" id="pass" class="passw"/>
        </div>
        <div class="actionBlock fix">
          <button type="submit" class="rgs frsBtn">Registrarse</button>
        </div>
      </form>
    </div>
  </div>
</div>